### ISSUE TITLE
fks causes R to crash

### ISSUE THREAD

**Issue by fuser-amirreza** [waternumbers/FKF#12]
Hello and thank you for this wonderful package. 

I am having issue using the fks function as it keeps crashing my R sessions. The crashes are occuring when I use the fkf and fks multiple times. For example, if I run a for loop that prepares the data for fkf, then runs fkf and fks, it causes R to crash after 3 or 4 iterations. If I run the same loop without fks, it runs fine and the kalman filter generates outputs that look fine.

My R version is 4.0.3 and I am using R's own BLAS and LAPACK packages.

**Comment by waternumbers** [comment]
Hi, sorry the package isn't working as intended

To help me look at the reason for the crash could you provide me with 
(a) the version number of FKF you are using - v0.2.3 fixed some issues with fks which might cause this behavior, if your not using it already I recommend upgrading to this version
(b) a reproducible example (ideally as an R script and data file)

It would be useful to know what platform (linux/windows/mac) you are using.

cheers

Paul

**Comment by fuser-amirreza** [comment]
Thanks so much for the quick response, Paul. 

Here is the information you requested:
(a) I am using v0.2.3
(b) The code is attached. In it, I have written a wrapper function around your fkf function, so that it could be used within mutate and group_by from dplyr. I have made sure the function works by running it through several tests. More importantly, the crash does not occur when I remove the use of fks from the function.
[sample_data.csv](https://github.com/waternumbers/FKF/files/8855379/sample_data.csv)
[sample_code_showing_fks_issue.zip](https://github.com/waternumbers/FKF/files/8855410/sample_code_showing_fks_issue.zip)
(c) I am on Windows 10 64-bit

**Comment by waternumbers** [comment]
Thanks will look at this asap (probably the weekend)

**Comment by fuser-amirreza** [comment]
Thanks very much! One thing I noticed is that it works very well when the number of sources is 1, but when it is higher than 1 it causes fks to crash R. Hope that helps!

**Comment by waternumbers** [comment]
Thanks for the update, that helped identify the problem. The FKF v0.2.3.1 should fix the problem and runs for me with your test data. You can install it from the source code on github or it is on my drat repository: https://waternumbers.github.io/drat/ (if you are on R4.0.* check which version it installs)

If this works for you then I'll close the issue update CRAN

**Comment by fuser-amirreza** [comment]
Thanks very much Paul! I will check right away and update you.

**Comment by fuser-amirreza** [comment]
Hey Paul, the function works great! Thanks again for the package and for fixing the issue!
