### ISSUE TITLE
Missing T_t factor when computing L in fks (fast kalman smoother) function

### ISSUE THREAD

**Issue by emmeranj** [waternumbers/FKF#6]
In the fast Kalman Smoother function, the update for L is L = Tt − Kt Zt, whereas I think it should perhaps be L = Tt − Tt Kt Zt.
If you look at page 7 (section IV, B) of the following paper, http://www.gatsby.ucl.ac.uk/~byron/nlds/briers04.pdf, which describes the update formuals for the forward-backward smoothing (in slightly different notation to the one of the documentation of this package). The update for L described there converted to the appropriate notation appears to be L = Tt − Tt Kt Zt. This makes sense because if you consider Tt = 0, i.e the state variables are independent, then the smoother and the filter should give the same output, namely Yt/2 for the smoother/filtered state variables and 1/2 for the corresponding variances. This is not the case for the current implementation of fks...

**Comment by waternumbers** [comment]
Yes you are correct - not sure where this error slipped during the development process - thanks for reporting it

An updated version of the package (v0.2.3) which should fix the resulting errors can be installed either from the main branch of the repo or prebuilt from:

https://waternumbers.github.io/drat/

If you get a chance to test it (and/or submit a further test for inclusion if you want) that would be great

For reference the smoother implementation follows pretty closely:

https://pure.uvt.nl/ws/portalfiles/portal/528557/18.pdf

**Comment by emmeranj** [comment]
Yes, it works now. Thanks a lot!
