### ISSUE TITLE
get fitted observations

### ISSUE THREAD

**Issue by AleBitetto** [waternumbers/FKF#9]
Hi,
first of all thanks for your package. I was trying to understand how the `vt` matrix of the prediction errors can be evaluated after fitting the `fkf` object. I tried to predict the fitted observations `yt_hat = ct + Zt * att` and to evaluate the residuals `yt - yt_hat` but I get different values. Any suggestions?
Thanks

**Comment by waternumbers** [comment]
You are computing the residuals using the filtered states `att`, where as `vt` is computed using the predicted (one step ahead) state estimate `at`.

**Comment by AleBitetto** [comment]
Thanks but the `at` has an extra timestep, how to reconcile with the input `yt`?

**Comment by waternumbers** [comment]
They are the step ahead prediction for the index: `at[,i]` is the step ahead prediction for time `i` generated at time `i-1`. The extra time step is the prediction for the time step after the end of your data.

**Comment by AleBitetto** [comment]
Thanks a lot for your explanation

**Comment by AleBitetto** [comment]
I have another question. Suppose I want to make a sensitivity analysis on the observed variables `yt` to understand which of its components is most affecting the estimation of the factors given the fixed `T` and `Z`. The aim is to evaluate a kind of features importance on the `yt`. So my idea is to keep `T` and `Z` fixed, to estimate the new smoothed factors `at`, evaluate the new residuals and compare them with the original ones. Suppose I change only the i-th variable in `yt`, I can evaluate the increase `Di` in the residuals compared to the original ones. Then I can rank the importance of the variables of `yt` by sorting `Di` from the highest to the lowest (the higher the worsening of the residuals, the more important/sensitive the variable is).

If this procedure makes sense, should I re-estimate the entire state space equations or can I somehow use the fitted `fkf` to "predict" with the new `yt`?

Hope it's clear and thanks in advance

**Comment by waternumbers** [comment]
Moved sensitivity analysis discussion to a new issue - please follow it there
